create or replace PROCEDURE "KHOASO_MULTIPLE_PERIOD" (P_TUKY IN NUMBER,P_DENKY IN NUMBER)
AS
    T_TABLENAME_KYTRUOC VARCHAR2(50);
    T_TABLENAME_KYNAY VARCHAR2(50);
    PARAM_TUKY NUMBER(18,2);
    PARAM_DENKY NUMBER(18,2);
BEGIN
    IF P_TUKY IS NULL THEN PARAM_TUKY := 1; 
    ELSE PARAM_TUKY := P_TUKY;
    END IF;
    IF P_DENKY IS NULL THEN PARAM_DENKY := PARAM_DENKY; 
    ELSE PARAM_DENKY := P_DENKY;
    END IF;
    FOR KY IN PARAM_TUKY..PARAM_DENKY
    LOOP
       T_TABLENAME_KYTRUOC := 'XNT_2019_KY_'||TO_NUMBER(KY-1)||'';
       T_TABLENAME_KYNAY := 'XNT_2019_KY_'||KY||'';
          BEGIN
            XUATNHAPTON.XNT_KHOASO(T_TABLENAME_KYTRUOC,T_TABLENAME_KYNAY,'01',2019,KY);
			EXECUTE IMMEDIATE 'UPDATE KYKETOAN SET TRANGTHAI = 10 WHERE KYKETOAN = '||KY||'';
            COMMIT;
          END;
    END LOOP;
END KHOASO_MULTIPLE_PERIOD;