create or replace PROCEDURE "KIEMTRA_TRUNGBARCODE_EXCEL" 
(
  P_MADONVI IN VARCHAR2 ,
  P_BARCODE IN VARCHAR2,
  CURSOR_RESULT OUT SYS_REFCURSOR
) AS 
  QUERY_SELECT VARCHAR2(1000);
  N_RESULT NUMBER(10,0) := 0;
  BARCODE_EXITS NUMBER(10,0) := 0;
BEGIN
  BEGIN
    IF P_BARCODE IS NOT NULL OR P_BARCODE != '' THEN
        IF INSTR(P_BARCODE,',') > 0 THEN
            BARCODE_EXITS := 0;
            FOR BARCODE_ROW IN (SELECT REGEXP_SUBSTR(''||P_BARCODE||'', '[^,]+', 1, LEVEL) AS BARCODE FROM DUAL CONNECT BY REGEXP_SUBSTR(''||P_BARCODE||'', '[^,]+', 1, LEVEL) IS NOT NULL)
            LOOP
                 QUERY_SELECT := 'SELECT COUNT(a.MAHANG) FROM( SELECT MAHANG,SUBSTR(BARCODE, INSTR(BARCODE, '''||BARCODE_ROW.BARCODE||'''), INSTR(BARCODE, '';'') - 1) AS BARCODE FROM MATHANG WHERE INSTR(BARCODE, '''||BARCODE_ROW.BARCODE||''') > 0 AND UNITCODE = '''||P_MADONVI||''') A WHERE LENGTH(A.BARCODE) = LENGTH('''||BARCODE_ROW.BARCODE||''')';
                 EXECUTE IMMEDIATE QUERY_SELECT INTO BARCODE_EXITS;
                 N_RESULT := N_RESULT + BARCODE_EXITS;
            END LOOP;
        ELSE
            QUERY_SELECT := 'SELECT COUNT(a.MAHANG) FROM( SELECT MAHANG,SUBSTR(BARCODE, INSTR(BARCODE, '''||P_BARCODE||'''), INSTR(BARCODE, '';'') - 1) AS BARCODE FROM MATHANG WHERE INSTR(BARCODE, '''||P_BARCODE||''') > 0 AND UNITCODE = '''||P_MADONVI||''') A WHERE LENGTH(A.BARCODE) = LENGTH('''||P_BARCODE||''')';
            EXECUTE IMMEDIATE QUERY_SELECT INTO N_RESULT;
        END IF;
    END IF;
  END;
  BEGIN
  OPEN CURSOR_RESULT FOR 'SELECT '||N_RESULT||' AS REFUND_DATA FROM DUAL';
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (SQLERRM);  
  END;
END KIEMTRA_TRUNGBARCODE_EXCEL;