create or replace PROCEDURE "TIMKIEM_CHUNGTU_PAGINATION" 
(
  P_MADONVI IN VARCHAR2 ,
  P_TUKHOA IN VARCHAR2,
  P_PAGENUMBER IN NUMBER,
  P_PAGESIZE IN NUMBER,
  P_LOAI_CHUNGTU IN VARCHAR2 ,
  P_TOTALITEM OUT SYS_REFCURSOR,
  CURSOR_RESULT OUT SYS_REFCURSOR
) AS
  STR_COUNT VARCHAR2(1000);
  STR_QUERY VARCHAR2(3000);
  QUERY_SELECT VARCHAR2(2000);
  T_LOAITIMKIEM VARCHAR2(20) := '';
  TEXT_IS_NUMBER NUMBER(18,2) := 0;
  IS_CONTAIN_UNITCODE VARCHAR2(2):='';
BEGIN
      SELECT IS_NUMBER(P_TUKHOA) INTO TEXT_IS_NUMBER FROM DUAL;
      BEGIN 
          SELECT * INTO IS_CONTAIN_UNITCODE FROM DUAL WHERE REGEXP_REPLACE(P_TUKHOA, '[^ -~]', '@') LIKE '%@%';
          EXCEPTION WHEN NO_DATA_FOUND
          THEN IS_CONTAIN_UNITCODE := '';
      END;
      IF LENGTH(P_TUKHOA) > 5 AND TEXT_IS_NUMBER = 1 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'BARCODE';
      END IF;
      IF LENGTH(P_TUKHOA) = 7 AND SUBSTR(P_TUKHOA,0,2) <> 'BH' AND TEXT_IS_NUMBER = 0 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'MAHANG';
      END IF;
      IF IS_NUMBER(SUBSTR(P_TUKHOA,0,1)) = 0 AND IS_NUMBER(SUBSTR(P_TUKHOA,2,LENGTH(P_TUKHOA))) = 1 
        THEN T_LOAITIMKIEM := 'MAHANG';
      END IF;
      IF IS_CONTAIN_UNITCODE = 'X' 
        THEN T_LOAITIMKIEM := 'TENHANG';
      END IF; 
      IF LENGTH(P_TUKHOA) = 4 AND INSTR(P_TUKHOA,P_LOAI_CHUNGTU) = 0  AND  TEXT_IS_NUMBER = 1 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'ITEMCODE';
      END IF;
      IF INSTR(P_TUKHOA,P_LOAI_CHUNGTU) > 0  AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'MA_CHUNGTU';
      END IF;
    
    IF T_LOAITIMKIEM = 'BARCODE' THEN
            QUERY_SELECT := '   SELECT f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG
                                FROM (
                                SELECT a.MAHANG,a.BARCODE
                                FROM MATHANG a INNER JOIN MATHANG_GIA b ON a.MAHANG = b.MAHANG  AND a.TRANGTHAI = b.TRANGTHAI 
                                AND a.TRANGTHAI = 10 AND a.UNITCODE = b.UNITCODE AND a.UNITCODE = '''||P_MADONVI||'''
                                ) e INNER JOIN (SELECT a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG,b.MAHANG
                                FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.UNITCODE = '''||P_MADONVI||''') f
                                ON e.MAHANG = f.MAHANG WHERE UPPER(e.BARCODE) LIKE ''%'||UPPER(P_TUKHOA)||'%'' AND f.LOAI_CHUNGTU = '''||P_LOAI_CHUNGTU||'''
                                GROUP BY f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG ';
            ELSIF T_LOAITIMKIEM = 'MAHANG' THEN
                QUERY_SELECT := '   SELECT f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG
                                FROM (
                                SELECT a.MAHANG
                                FROM MATHANG a INNER JOIN MATHANG_GIA b ON a.MAHANG = b.MAHANG  AND a.TRANGTHAI = b.TRANGTHAI 
                                AND a.TRANGTHAI = 10 AND a.UNITCODE = b.UNITCODE AND a.UNITCODE = '''||P_MADONVI||'''
                                ) e INNER JOIN (SELECT a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG,b.MAHANG
                                FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.UNITCODE = '''||P_MADONVI||''') f
                                ON e.MAHANG = f.MAHANG WHERE UPPER(e.MAHANG) LIKE ''%'||UPPER(P_TUKHOA)||'%'' AND f.LOAI_CHUNGTU = '''||P_LOAI_CHUNGTU||'''
                                GROUP BY f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG ';
            ELSIF T_LOAITIMKIEM = 'TENHANG' THEN
                QUERY_SELECT := '   SELECT f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG
                                FROM (
                                SELECT a.MAHANG,a.TENHANG
                                FROM MATHANG a INNER JOIN MATHANG_GIA b ON a.MAHANG = b.MAHANG  AND a.TRANGTHAI = b.TRANGTHAI 
                                AND a.TRANGTHAI = 10 AND a.UNITCODE = b.UNITCODE AND a.UNITCODE = '''||P_MADONVI||'''
                                ) e INNER JOIN (SELECT a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG,b.MAHANG
                                FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.UNITCODE = '''||P_MADONVI||''') f
                                ON e.MAHANG = f.MAHANG WHERE UPPER(e.TENHANG) LIKE N''%'||UPPER(P_TUKHOA)||'%'' AND f.LOAI_CHUNGTU = '''||P_LOAI_CHUNGTU||'''
                                GROUP BY f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG ';
            ELSIF T_LOAITIMKIEM = 'ITEMCODE' THEN
                QUERY_SELECT := '   SELECT f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG
                                FROM (
                                SELECT a.MAHANG,a.ITEMCODE
                                FROM MATHANG a INNER JOIN MATHANG_GIA b ON a.MAHANG = b.MAHANG  AND a.TRANGTHAI = b.TRANGTHAI 
                                AND a.TRANGTHAI = 10 AND a.UNITCODE = b.UNITCODE AND a.UNITCODE = '''||P_MADONVI||'''
                                ) e INNER JOIN (SELECT a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG,b.MAHANG
                                FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.UNITCODE = '''||P_MADONVI||''') f
                                ON e.MAHANG = f.MAHANG WHERE UPPER(e.ITEMCODE) = N''%'||UPPER(P_TUKHOA)||'%'' AND f.LOAI_CHUNGTU = '''||P_LOAI_CHUNGTU||'''
                                GROUP BY f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG ';
            ELSIF T_LOAITIMKIEM = 'MA_CHUNGTU' THEN
                QUERY_SELECT := '   SELECT a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG
                                FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.UNITCODE = '''||P_MADONVI||''' AND UPPER(a.MA_CHUNGTU) LIKE N''%'||UPPER(P_TUKHOA)||'%'' AND a.LOAI_CHUNGTU = '''||P_LOAI_CHUNGTU||'''
                                GROUP BY a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,a.NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG ';
            ELSE 
                QUERY_SELECT := '   SELECT f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG
                                FROM (
                                SELECT a.MAHANG,a.TENHANG
                                FROM MATHANG a INNER JOIN MATHANG_GIA b ON a.MAHANG = b.MAHANG  AND a.TRANGTHAI = b.TRANGTHAI 
                                AND a.TRANGTHAI = 10 AND a.UNITCODE = b.UNITCODE AND a.UNITCODE = '''||P_MADONVI||'''
                                ) e INNER JOIN (SELECT a.ID,a.LOAI_CHUNGTU,a.MA_CHUNGTU,NGAY_CHUNGTU,a.NGAY_DUYETPHIEU,a.MAKHO_NHAP,a.MAKHO_XUAT,a.TRANGTHAI,a.MANHACUNGCAP,a.MAKHACHHANG,b.MAHANG
                                FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.UNITCODE = '''||P_MADONVI||''') f
                                ON e.MAHANG = f.MAHANG WHERE UPPER(e.TENHANG) LIKE N''%'||UPPER(P_TUKHOA)||'%'' AND f.LOAI_CHUNGTU = '''||P_LOAI_CHUNGTU||'''
                                GROUP BY f.ID,f.MA_CHUNGTU,f.NGAY_CHUNGTU,f.NGAY_DUYETPHIEU,f.MAKHO_NHAP,f.MAKHO_XUAT,f.TRANGTHAI,f.MANHACUNGCAP,f.MAKHACHHANG ';
    END IF;
--     DBMS_OUTPUT.PUT_LINE(QUERY_SELECT);
    BEGIN
    OPEN P_TOTALITEM FOR 'SELECT COUNT(*) AS TOTAL_ITEM FROM ('||QUERY_SELECT||')';
    EXCEPTION WHEN OTHERS THEN 
    GOTO countinus;
    END;
    <<countinus>>
    STR_QUERY:= 'SELECT * FROM
    (
        SELECT a.*, rownum r__
        FROM
        (
            '||QUERY_SELECT||'
        ) a
        WHERE rownum < (('||P_PAGENUMBER||' * '||P_PAGESIZE||') + 1 )
    )
    WHERE r__ >= ((('||P_PAGENUMBER||'-1) * '||P_PAGESIZE||') + 1)';
            OPEN CURSOR_RESULT FOR STR_QUERY;    
            EXCEPTION WHEN OTHERS THEN COMMIT;
END TIMKIEM_CHUNGTU_PAGINATION;