create or replace PROCEDURE "TIMKIEM_KHACHHANG"
(
  P_KEYSEARCH IN VARCHAR2,
  P_UNITCODE IN VARCHAR2,
  -- 1 là có sử dụng tìm kiếm all
  -- 0 là sử dụng tìm kiếm theo tiêu chí
  P_USE_TIMKIEM_ALL IN NUMBER,
  P_DIEUKIEN_TIMKIEM IN NUMBER,
  CURSOR_RESULT OUT SYS_REFCURSOR
) AS 
  QUERY_SELECT VARCHAR2(3000);
  P_WHERE VARCHAR2(3000);
  TEXT_IS_NUMBER NUMBER(18,2) := 0;
  IS_CONTAIN_UNITCODE VARCHAR2(2):='';
BEGIN
  IF P_KEYSEARCH IS NULL OR P_KEYSEARCH = '' THEN P_WHERE := ' 1 = 1 AND ';
  END IF;
  SELECT IS_NUMBER(P_KEYSEARCH) INTO TEXT_IS_NUMBER FROM DUAL;
  BEGIN 
      SELECT * INTO IS_CONTAIN_UNITCODE FROM DUAL WHERE REGEXP_REPLACE(P_KEYSEARCH, '[^ -~]', '@') LIKE '%@%';
      EXCEPTION WHEN NO_DATA_FOUND
      THEN IS_CONTAIN_UNITCODE := '';
  END;
IF P_USE_TIMKIEM_ALL = 1 THEN
    BEGIN
            -- TÌM KIẾM THEO MÃ KHÁCH HÀNG
          IF SUBSTR(P_KEYSEARCH,0,3) = 'VIP' THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO MÃ KHÁCH HÀNG');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE '|| P_WHERE ||' UPPER(MAKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY MAKHACHHANG';
          -- TÌM KIẾM THEO TÊN KHÁCH HÀNG
          ELSIF IS_CONTAIN_UNITCODE = 'X' THEN
           DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO TÊN KHÁCH HÀNG');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UPPER(TENKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY TENKHACHHANG';
          -- TÌM KIẾM THEO SỐ ĐIỆN THOẠI
          ELSIF TEXT_IS_NUMBER = 1 AND (LENGTH(P_KEYSEARCH) = 11 OR LENGTH(P_KEYSEARCH) = 10)  THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO SỐ ĐIỆN THOẠI');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UPPER(UNITCODE) = '''||UPPER(P_UNITCODE)||''' AND (UPPER(DIENTHOAI) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'') ORDER BY DIENTHOAI';
          -- TÌM KIẾM THEO SỐ CHỨNG MINH THƯ NHÂN DÂN
          ELSIF TEXT_IS_NUMBER = 1 AND (LENGTH(P_KEYSEARCH) = 9 OR LENGTH(P_KEYSEARCH) = 12)  THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO SỐ CHỨNG MINH THƯ NHÂN DÂN');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE 
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' (UPPER(CANCUOC_CONGDAN) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' OR UPPER(MATHE) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' ) AND UNITCODE = '''||P_UNITCODE||''' ORDER BY CANCUOC_CONGDAN';
           -- TÌM KIẾM THEO SỐ ĐIỂM  
          ELSIF TEXT_IS_NUMBER = 1 AND LENGTH(P_KEYSEARCH) < 9  THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO SỐ ĐIỂM');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UPPER(SODIEM) = '||UPPER(P_KEYSEARCH)||' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY SODIEM';
          ELSE
            DBMS_OUTPUT.PUT_LINE('TÌM KIẾM MẶC ĐỊNH');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' ( UPPER(MAKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' 
                            OR UPPER(DIENTHOAI) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' OR UPPER(CANCUOC_CONGDAN) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' 
                            OR UPPER(TENKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' OR UPPER(MATHE) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' ) 
                            AND UNITCODE = '''||P_UNITCODE||''' ';
        END IF;     
    END;                
ELSE
    BEGIN
            -- TÌM KIẾM THEO MÃ KHÁCH HÀNG
          IF P_DIEUKIEN_TIMKIEM = 0 THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO MÃ THẺ');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE '|| P_WHERE ||' UPPER(MATHE) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY MATHE';
          -- TÌM KIẾM THEO TÊN KHÁCH HÀNG
          ELSIF P_DIEUKIEN_TIMKIEM = 1 THEN
           DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO MÃ KHÁCH HÀNG');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UPPER(MAKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY MAKHACHHANG';
          -- TÌM KIẾM THEO TÊN KHÁCH HÀNG
          ELSIF P_DIEUKIEN_TIMKIEM = 2 THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO TÊN KHÁCH HÀNG');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UNITCODE = '''||P_UNITCODE||''' AND (UPPER(TENKHACHHANG) LIKE N''%'||UPPER(P_KEYSEARCH)||'%'') ';
          -- TÌM KIẾM THEO SỐ ĐIỆN THOẠI
          ELSIF P_DIEUKIEN_TIMKIEM = 3 THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO SỐ ĐIỆN THOẠI');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UNITCODE = '''||P_UNITCODE||''' AND (UPPER(DIENTHOAI) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'') ORDER BY DIENTHOAI';
          -- TÌM KIẾM THEO SỐ CHỨNG MINH THƯ NHÂN DÂN
          ELSIF P_DIEUKIEN_TIMKIEM = 4 THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO SỐ CHỨNG MINH THƯ NHÂN DÂN');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UPPER(CANCUOC_CONGDAN) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY CANCUOC_CONGDAN';
           -- TÌM KIẾM THEO SỐ ĐIỂM 
          ELSIF P_DIEUKIEN_TIMKIEM = 5 THEN
          DBMS_OUTPUT.PUT_LINE('TÌM KIẾM THEO SỐ ĐIỂM');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' UPPER(SODIEM) = '||UPPER(P_KEYSEARCH)||' AND UNITCODE = '''||P_UNITCODE||''' ORDER BY SODIEM';
          ELSE
            DBMS_OUTPUT.PUT_LINE('TÌM KIẾM MẶC ĐỊNH');
           QUERY_SELECT := 'SELECT MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI,CANCUOC_CONGDAN,NGAYSINH,NGAYDACBIET,MATHE,SODIEM,TONGTIEN,DIENGIAI,TRANGTHAI,I_CREATE_DATE
                            FROM KHACHHANG 
                            WHERE  '|| P_WHERE ||' ( UPPER(MAKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' OR UPPER(DIENTHOAI) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' 
                            OR UPPER(CANCUOC_CONGDAN) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' OR UPPER(TENKHACHHANG) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' OR UPPER(MATHE) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' ) 
                            AND UNITCODE = '''||P_UNITCODE||''' ';
        END IF;
    END;
END IF;
    --DBMS_OUTPUT.PUT_LINE('QUERY_SELECT:'||QUERY_SELECT);
  BEGIN
  OPEN CURSOR_RESULT FOR QUERY_SELECT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (SQLERRM);  
  END;
END TIMKIEM_KHACHHANG;
 