create or replace PROCEDURE "TIMKIEM_KHUYENMAI_PAGINATION" 
(
  P_MADONVI IN VARCHAR2 ,
  P_TUKHOA IN VARCHAR2,
  P_PAGENUMBER IN NUMBER,
  P_PAGESIZE IN NUMBER,
  P_LOAI_KHUYENMAI IN VARCHAR2 ,
  P_TOTALITEM OUT SYS_REFCURSOR,
  CURSOR_RESULT OUT SYS_REFCURSOR
) AS
  STR_COUNT VARCHAR2(1000);
  STR_QUERY VARCHAR2(3000);
  QUERY_SELECT VARCHAR2(2000);
  T_LOAITIMKIEM VARCHAR2(20) := '';
  TEXT_IS_NUMBER NUMBER(18,2) := 0;
  IS_CONTAIN_UNITCODE VARCHAR2(2):='';
BEGIN
      SELECT IS_NUMBER(P_TUKHOA) INTO TEXT_IS_NUMBER FROM DUAL;
      BEGIN 
          SELECT * INTO IS_CONTAIN_UNITCODE FROM DUAL WHERE REGEXP_REPLACE(P_TUKHOA, '[^ -~]', '@') LIKE '%@%';
          EXCEPTION WHEN NO_DATA_FOUND
          THEN IS_CONTAIN_UNITCODE := '';
      END;
      IF IS_CONTAIN_UNITCODE = 'X' 
        THEN T_LOAITIMKIEM := 'DIENGIAI';
      END IF; 
      IF TEXT_IS_NUMBER = 0 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '')
        THEN T_LOAITIMKIEM := 'DIENGIAI';
      END IF;
      IF INSTR(P_TUKHOA,P_LOAI_KHUYENMAI) = 0  AND  TEXT_IS_NUMBER = 1 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'MAKHUYENMAI';
      END IF;
--     DBMS_OUTPUT.PUT_LINE('T_LOAITIMKIEM:'||T_LOAITIMKIEM);
            IF  T_LOAITIMKIEM = 'MAKHUYENMAI' THEN
            QUERY_SELECT := 'SELECT a.ID,a.MA_KHUYENMAI,a.TUNGAY,a.DENNGAY,a.TUGIO,a.DENGIO,a.MAKHO_KHUYENMAI,a.DIENGIAI,a.TRANGTHAI,a.UNITCODE,a.I_CREATE_DATE,a.THOIGIAN_TAO FROM KHUYENMAI a WHERE  a.LOAI_KHUYENMAI = '''||P_LOAI_KHUYENMAI||''' AND a.UNITCODE = '''||P_MADONVI||''' AND UPPER(a.MA_KHUYENMAI) LIKE ''%'||UPPER(P_TUKHOA)||'%'' ORDER BY a.MA_KHUYENMAI';
            ELSIF T_LOAITIMKIEM = 'DIENGIAI' THEN
            QUERY_SELECT := 'SELECT a.ID,a.MA_KHUYENMAI,a.TUNGAY,a.DENNGAY,a.TUGIO,a.DENGIO,a.MAKHO_KHUYENMAI,a.DIENGIAI,a.TRANGTHAI,a.UNITCODE,a.I_CREATE_DATE,a.THOIGIAN_TAO FROM KHUYENMAI a WHERE  a.LOAI_KHUYENMAI = '''||P_LOAI_KHUYENMAI||''' AND a.UNITCODE = '''||P_MADONVI||''' AND UPPER(a.DIENGIAI) LIKE N''%'||UPPER(P_TUKHOA)||'%'' ORDER BY a.MA_KHUYENMAI';
            ELSE 
            QUERY_SELECT := 'SELECT a.ID,a.MA_KHUYENMAI,a.TUNGAY,a.DENNGAY,a.TUGIO,a.DENGIO,a.MAKHO_KHUYENMAI,a.DIENGIAI,a.TRANGTHAI,a.UNITCODE,a.I_CREATE_DATE,a.THOIGIAN_TAO FROM KHUYENMAI a WHERE  a.LOAI_KHUYENMAI = '''||P_LOAI_KHUYENMAI||''' AND a.UNITCODE = '''||P_MADONVI||''' ORDER BY a.MA_KHUYENMAI';
    END IF;
    DBMS_OUTPUT.PUT_LINE('QUERY_SELECT:'||QUERY_SELECT);
    BEGIN
    OPEN P_TOTALITEM FOR 'SELECT COUNT(*) AS TOTAL_ITEM FROM ('||QUERY_SELECT||')';
    EXCEPTION WHEN OTHERS THEN 
    GOTO countinus;
    END;
    <<countinus>>
    STR_QUERY:= 'SELECT * FROM
    (
        SELECT a.*, rownum r__
        FROM
        (
            '||QUERY_SELECT||'
        ) a
        WHERE rownum < (('||P_PAGENUMBER||' * '||P_PAGESIZE||') + 1 )
    )
    WHERE r__ >= ((('||P_PAGENUMBER||'-1) * '||P_PAGESIZE||') + 1)';
            OPEN CURSOR_RESULT FOR STR_QUERY;    
            EXCEPTION WHEN OTHERS THEN COMMIT;
END TIMKIEM_KHUYENMAI_PAGINATION;
 