create or replace PROCEDURE "TIMKIEM_GIAODICHQUAY"
(
  P_KEYSEARCH IN VARCHAR2 ,
  P_TUNGAY IN OUT DATE,
  P_DENNGAY IN OUT DATE,
  P_DIEUKIENLOC IN OUT NUMBER,
  P_UNITCODE IN VARCHAR2,
  CURSOR_RESULT OUT SYS_REFCURSOR
) AS 
  QUERY_SELECT VARCHAR2(3000);
BEGIN
  IF P_TUNGAY IS NULL OR P_TUNGAY = '' THEN P_TUNGAY := SYSDATE;
  END IF;
  IF P_DENNGAY IS NULL OR P_DENNGAY = '' THEN P_DENNGAY := SYSDATE;
  END IF;
  IF P_DIEUKIENLOC IS NULL OR P_DIEUKIENLOC = '' THEN P_DIEUKIENLOC := '0';
  END IF;
  -- TÌM KIẾM THEO MÃ GIAO DỊCH
  IF P_DIEUKIENLOC = '0' THEN
   QUERY_SELECT := 'SELECT a.MA_GIAODICH,a.LOAI_GIAODICH,a.I_CREATE_DATE,a.I_CREATE_BY,
                    a.NGAY_GIAODICH,a.MA_VOUCHER,a.TIENKHACH_TRA,a.TIEN_TRALAI_KHACH,
                    SUM(b.TIEN_VOUCHER) AS TIEN_VOUCHER,SUM(b.TIENTHE_VIP) AS TIENTHE,
                    SUM(b.THANHTIEN) AS THANHTIEN,a.THOIGIAN_TAO,a.MAKHACHHANG,a.UNITCODE
                    FROM GIAODICH a INNER JOIN GIAODICH_CHITIET b ON a.MA_GIAODICH = b.MA_GIAODICH
                    WHERE a.MA_GIAODICH LIKE ''%'||P_KEYSEARCH||'%'' AND TO_DATE(a.NGAY_GIAODICH,''DD-MM-YY'') >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                    AND TO_DATE(a.NGAY_GIAODICH,''DD-MM-YY'') <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND UNITCODE = '''||P_UNITCODE||'''
                    GROUP BY a.MA_GIAODICH,a.LOAI_GIAODICH,a.I_CREATE_DATE,a.I_CREATE_BY,
                    a.NGAY_GIAODICH,a.MA_VOUCHER,a.TIENKHACH_TRA,a.TIEN_TRALAI_KHACH,
                    a.THOIGIAN_TAO,a.MAKHACHHANG,a.UNITCODE
                    ORDER BY a.THOIGIAN_TAO DESC';
  -- TÌM KIẾM THEO SỐ TIỀN
  ELSIF P_DIEUKIENLOC = '1' THEN
   QUERY_SELECT := 'SELECT c.MA_GIAODICH,c.LOAI_GIAODICH,c.I_CREATE_DATE,c.I_CREATE_BY,
                    c.NGAY_GIAODICH,c.MA_VOUCHER,c.TIENKHACH_TRA,c.TIEN_TRALAI_KHACH,
                    c.TIEN_VOUCHER,c.TIENTHE_VIP AS TIENTHE,c.THANHTIEN,c.THOIGIAN_TAO,c.MAKHACHHANG,c.UNITCODE
                    FROM
                    (SELECT a.MA_GIAODICH,a.LOAI_GIAODICH,a.I_CREATE_DATE,a.I_CREATE_BY,
                    a.NGAY_GIAODICH,a.MA_VOUCHER,a.TIENKHACH_TRA,a.TIEN_TRALAI_KHACH,
                    SUM(b.TIEN_VOUCHER) AS TIEN_VOUCHER,SUM(b.TIENTHE_VIP) AS TIENTHE_VIP,
                    SUM(b.THANHTIEN) AS THANHTIEN,a.THOIGIAN_TAO,a.MAKHACHHANG,a.UNITCODE
                    FROM GIAODICH a INNER JOIN GIAODICH_CHITIET b ON a.MA_GIAODICH = b.MA_GIAODICH
                    WHERE TO_DATE(a.NGAY_GIAODICH,''DD-MM-YY'') >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                    AND TO_DATE(a.NGAY_GIAODICH,''DD-MM-YY'') <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') 
                    AND a.UNITCODE = '''||P_UNITCODE||''' 
                    GROUP BY a.MA_GIAODICH,a.LOAI_GIAODICH,a.I_CREATE_DATE,a.I_CREATE_BY,
                    a.NGAY_GIAODICH,a.MA_VOUCHER,a.TIENKHACH_TRA,a.TIEN_TRALAI_KHACH,
                    a.THOIGIAN_TAO,a.MAKHACHHANG,a.UNITCODE
                    ) c WHERE c.THANHTIEN = TO_NUMBER('||P_KEYSEARCH||') ORDER BY c.THOIGIAN_TAO DESC';
   -- TÌM KIẾM THEO THU NGÂN TẠO   
  ELSE
   QUERY_SELECT := 'SELECT c.MA_GIAODICH,c.LOAI_GIAODICH,c.I_CREATE_DATE,c.I_CREATE_BY,
                    c.NGAY_GIAODICH,c.MA_VOUCHER,c.TIENKHACH_TRA,c.TIEN_TRALAI_KHACH,
                    c.TIEN_VOUCHER,c.TIENTHE_VIP AS TIENTHE,c.THANHTIEN,c.THOIGIAN_TAO,c.MAKHACHHANG,c.UNITCODE 
                    FROM (SELECT a.MA_GIAODICH,a.LOAI_GIAODICH,a.I_CREATE_DATE,a.I_CREATE_BY,
                    a.NGAY_GIAODICH,a.MA_VOUCHER,a.TIENKHACH_TRA,a.TIEN_TRALAI_KHACH,
                    SUM(b.TIEN_VOUCHER) AS TIEN_VOUCHER,SUM(b.TIENTHE_VIP) AS TIENTHE_VIP,
                    SUM(b.THANHTIEN) AS THANHTIEN,a.THOIGIAN_TAO,a.MAKHACHHANG,a.UNITCODE
                    FROM GIAODICH a INNER JOIN GIAODICH_CHITIET b ON a.MA_GIAODICH = b.MA_GIAODICH
                    WHERE TO_DATE(a.NGAY_GIAODICH,''DD-MM-YY'') >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                    AND TO_DATE(a.NGAY_GIAODICH,''DD-MM-YY'') <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND UNITCODE = '''||P_UNITCODE||'''
                    GROUP BY a.MA_GIAODICH,a.LOAI_GIAODICH,a.I_CREATE_DATE,a.I_CREATE_BY,
                    a.NGAY_GIAODICH,a.MA_VOUCHER,a.TIENKHACH_TRA,a.TIEN_TRALAI_KHACH,
                    a.THOIGIAN_TAO,a.MAKHACHHANG,a.UNITCODE)
                    c INNER JOIN NGUOIDUNG d ON c.I_CREATE_BY = d.MANHANVIEN 
                    WHERE UPPER(d.TENNHANVIEN) LIKE ''%'||UPPER(P_KEYSEARCH)||'%'' ORDER BY c.THOIGIAN_TAO DESC';
  END IF;
    DBMS_OUTPUT.PUT_LINE('QUERY_SELECT:'||QUERY_SELECT);
  BEGIN
  OPEN CURSOR_RESULT FOR QUERY_SELECT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (SQLERRM);  
  END;
END TIMKIEM_GIAODICHQUAY;