create or replace PROCEDURE "UPDATE_GIA_SAUDUYET_NHAPMUA" 
(
  P_MADONVI IN VARCHAR2 ,
  P_ID IN VARCHAR2,
  P_RESULT_UPDATE OUT SYS_REFCURSOR
) AS
  STR_QUERY VARCHAR2(500);
  CURSOR_VOUCHER SYS_REFCURSOR;
  MAHANG VARCHAR2(20) := '';
  GIAMUA NUMBER(18,2) := 0;
  GIAMUA_VAT NUMBER(18,2) := 0;
  N_UPDATE NUMBER(10,0) := 0;
BEGIN
    OPEN CURSOR_VOUCHER FOR 'SELECT b.MAHANG,b.GIAMUA,b.GIAMUA_VAT FROM CHUNGTU a INNER JOIN CHUNGTU_CHITIET b ON a.MA_CHUNGTU = b.MA_CHUNGTU AND a.ID = '''||P_ID||''' AND a.UNITCODE = '''||P_MADONVI||''' ';
    LOOP
       FETCH CURSOR_VOUCHER INTO MAHANG,GIAMUA,GIAMUA_VAT;
       EXIT WHEN CURSOR_VOUCHER%NOTFOUND;
       -- neu gia mua = 0 thi gan lai gia mua bang 1
       IF (GIAMUA = 0 OR GIAMUA IS NULL) THEN GIAMUA := 1; END IF;
       STR_QUERY := 'UPDATE MATHANG_GIA SET GIAMUA = '||GIAMUA||', GIAMUA_VAT = '||GIAMUA_VAT||', TYLE_LAILE = ROUND(100 * ((100 * (GIABANLE - '||GIAMUA||')) / '||GIAMUA||')) / 100 , TYLE_LAIBUON = ROUND(100 * ((100 * (GIABANBUON - '||GIAMUA||')) / '||GIAMUA||')) / 100 WHERE MAHANG = '''||MAHANG||''' AND UNITCODE = '''||P_MADONVI||''' ';
       EXECUTE IMMEDIATE STR_QUERY;
       N_UPDATE := N_UPDATE + 1;
    END LOOP;
    OPEN P_RESULT_UPDATE FOR 'SELECT '||N_UPDATE||' AS RESULT_UPDATE FROM DUAL' ;        
        EXCEPTION
           WHEN NO_DATA_FOUND
           THEN
              DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
           WHEN OTHERS
           THEN
              DBMS_OUTPUT.put_line ('ERROR'  || SQLERRM);   
END UPDATE_GIA_SAUDUYET_NHAPMUA;