create or replace PROCEDURE "XUATNHAPTON_TONKHO_CHITIET"(TABLE_NAME IN VARCHAR2,DIEUKIEN_NHOM IN VARCHAR2,MAKHO IN VARCHAR2,MALOAI IN VARCHAR2,MANHOM IN VARCHAR2,MANHACUNGCAP IN VARCHAR2,MAHANG IN VARCHAR2,UNITCODE IN VARCHAR2,USERNAME IN VARCHAR2, CUR_OUT OUT SYS_REFCURSOR) AS
    QUERY_STR VARCHAR(2000);
    QUERY_SELECT VARCHAR(500);
    QUERY_WHERE_IN VARCHAR(500) := '';
    QUERY_GROUPBY VARCHAR(500) := '';
    QUERY_ORDERBY VARCHAR(200) := '';
    TABLE_JOIN VARCHAR(500) := '';
BEGIN
    IF MAKHO IS NOT NULL OR MAKHO != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND xnt.MAKHO IN (SELECT REGEXP_SUBSTR('''||MAKHO||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MAKHO||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MALOAI IS NOT NULL OR MALOAI != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND loaihang.MALOAI IN (SELECT REGEXP_SUBSTR('''||MALOAI||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MALOAI||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MANHOM IS NOT NULL OR MANHOM != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND nhomhang.MANHOM IN (SELECT REGEXP_SUBSTR('''||MANHOM||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MANHOM||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MANHACUNGCAP IS NOT NULL OR MANHACUNGCAP != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND mathang.MANHACUNGCAP IN (SELECT REGEXP_SUBSTR('''||MANHACUNGCAP||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MANHACUNGCAP||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MAHANG IS NOT NULL OR MAHANG != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND xnt.MAHANG IN (SELECT REGEXP_SUBSTR('''||MAHANG||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MAHANG||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;

    IF DIEUKIEN_NHOM = 'KHOHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' xnt.MAKHO AS MA,khohang.TENKHO AS TEN, xnt.MAHANG AS MACON, mathang.TENHANG AS TENCON, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE   ';
        TABLE_JOIN := ' INNER JOIN KHOHANG khohang ON xnt.MAKHO = khohang.MAKHO INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN MATHANG_GIA mathang_gia ON mathang.MAHANG = mathang_gia.MAHANG 
        INNER JOIN LOAIHANG loaihang ON mathang.MALOAI = loaihang.MALOAI INNER JOIN NHACUNGCAP nhacungcap ON mathang.MANHACUNGCAP = nhacungcap.MANHACUNGCAP INNER JOIN NHOMHANG nhomhang ON mathang.MANHOM = nhomhang.MANHOM ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY xnt.MAKHO,khohang.TENKHO, xnt.MAHANG, mathang.TENHANG ,xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE' ;
        QUERY_ORDERBY := ' ORDER BY xnt.MAKHO,xnt.MAHANG';
    ELSIF DIEUKIEN_NHOM = 'LOAIHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' mathang.MALOAI AS MA,loaihang.TENLOAI AS TEN, xnt.MAHANG AS MACON, mathang.TENHANG AS TENCON, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE   ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN LOAIHANG loaihang ON mathang.MALOAI = loaihang.MALOAI INNER JOIN MATHANG_GIA mathang_gia ON mathang.MAHANG = mathang_gia.MAHANG
        INNER JOIN KHOHANG khohang ON xnt.MAKHO = khohang.MAKHO INNER JOIN NHACUNGCAP nhacungcap ON mathang.MANHACUNGCAP = nhacungcap.MANHACUNGCAP INNER JOIN NHOMHANG nhomhang ON mathang.MANHOM = nhomhang.MANHOM  ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY mathang.MALOAI,loaihang.TENLOAI, xnt.MAHANG, mathang.TENHANG ,xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE' ;
        QUERY_ORDERBY := ' ORDER BY mathang.MALOAI,xnt.MAHANG';
    ELSIF DIEUKIEN_NHOM = 'NHOMHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' mathang.MANHOM AS MA,nhomhang.TENNHOM AS TEN, xnt.MAHANG AS MACON, mathang.TENHANG AS TENCON, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN NHOMHANG nhomhang ON mathang.MANHOM = nhomhang.MANHOM INNER JOIN MATHANG_GIA mathang_gia ON mathang.MAHANG = mathang_gia.MAHANG
        INNER JOIN KHOHANG khohang ON xnt.MAKHO = khohang.MAKHO INNER JOIN NHACUNGCAP nhacungcap ON mathang.MANHACUNGCAP = nhacungcap.MANHACUNGCAP INNER JOIN LOAIHANG loaihang ON mathang.MALOAI = loaihang.MALOAI ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY mathang.MANHOM,nhomhang.TENNHOM, xnt.MAHANG, mathang.TENHANG, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE' ;
        QUERY_ORDERBY := ' ORDER BY mathang.MANHOM,xnt.MAHANG';
    ELSIF DIEUKIEN_NHOM = 'NHACUNGCAP' THEN
        QUERY_SELECT := QUERY_SELECT || ' mathang.MANHACUNGCAP AS MA,nhacungcap.TENNHACUNGCAP AS TEN, xnt.MAHANG AS MACON, mathang.TENHANG AS TENCON, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN NHACUNGCAP nhacungcap ON mathang.MANHACUNGCAP = nhacungcap.MANHACUNGCAP INNER JOIN MATHANG_GIA mathang_gia ON mathang.MAHANG = mathang_gia.MAHANG
        INNER JOIN KHOHANG khohang ON xnt.MAKHO = khohang.MAKHO INNER JOIN LOAIHANG loaihang ON mathang.MALOAI = loaihang.MALOAI INNER JOIN NHOMHANG nhomhang ON mathang.MANHOM = nhomhang.MANHOM ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY mathang.MANHACUNGCAP,nhacungcap.TENNHACUNGCAP, xnt.MAHANG, mathang.TENHANG ,xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE' ;
        QUERY_ORDERBY := ' ORDER BY mathang.MANHACUNGCAP,xnt.MAHANG';
    ELSIF DIEUKIEN_NHOM = 'MATHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' xnt.MAHANG AS MA,mathang.TENHANG AS TEN, xnt.MAKHO AS MACON, khohang.TENKHO AS TENCON, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN MATHANG_GIA mathang_gia ON mathang.MAHANG = mathang_gia.MAHANG INNER JOIN KHOHANG khohang ON xnt.MAKHO = khohang.MAKHO';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY xnt.MAHANG, mathang.TENHANG, xnt.MAKHO, khohang.TENKHO, xnt.GIAVON, xnt.TONCUOIKYSL, xnt.TONCUOIKYGT, mathang_gia.GIAMUA, mathang_gia.GIABANLE ' ;
        QUERY_ORDERBY := ' ORDER BY xnt.MAHANG,xnt.MAKHO';
    ELSE
        QUERY_GROUPBY := QUERY_GROUPBY || ' 1 AND 1 ';
    END IF;

    QUERY_STR := 'SELECT '||QUERY_SELECT||' 
    FROM '||TABLE_NAME||' xnt '||TABLE_JOIN||' '||QUERY_WHERE_IN||'
    WHERE xnt.UNITCODE = '''||UNITCODE||''' '||QUERY_GROUPBY || QUERY_ORDERBY ||'';
    BEGIN
    DBMS_OUTPUT.put_line (QUERY_STR);  
    OPEN CUR_OUT FOR QUERY_STR;
    EXCEPTION
                WHEN NO_DATA_FOUND THEN
                 NULL;
                   WHEN OTHERS THEN
          NULL;
    END;
END XUATNHAPTON_TONKHO_CHITIET;