create or replace PROCEDURE "XUATNHAPTON_TONKHO_TONGHOP"(TABLE_NAME IN VARCHAR2,DIEUKIEN_NHOM IN VARCHAR2,MAKHO IN VARCHAR2,MALOAI IN VARCHAR2,MANHOM IN VARCHAR2,MANHACUNGCAP IN VARCHAR2,MAHANG IN VARCHAR2,UNITCODE IN VARCHAR2,USERNAME IN VARCHAR2, CUR_OUT OUT SYS_REFCURSOR) AS
    QUERY_STR VARCHAR(2000);
    QUERY_SELECT VARCHAR(500);
    QUERY_WHERE_IN VARCHAR(500) := '';
    QUERY_GROUPBY VARCHAR(500) := '';
    QUERY_ORDERBY VARCHAR(200) := '';
    TABLE_JOIN VARCHAR(500) := '';
BEGIN
    IF MAKHO IS NOT NULL OR MAKHO != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND xnt.MAKHO IN (SELECT REGEXP_SUBSTR('''||MAKHO||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MAKHO||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MALOAI IS NOT NULL OR MALOAI != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND loaihang.MALOAI IN (SELECT REGEXP_SUBSTR('''||MALOAI||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MALOAI||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MANHOM IS NOT NULL OR MANHOM != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND nhomhang.MANHOM IN (SELECT REGEXP_SUBSTR('''||MANHOM||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MANHOM||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MANHACUNGCAP IS NOT NULL OR MANHACUNGCAP != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND nhacungcap.MANHACUNGCAP IN (SELECT REGEXP_SUBSTR('''||MANHACUNGCAP||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MANHACUNGCAP||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    IF MAHANG IS NOT NULL OR MAHANG != '' THEN
        QUERY_WHERE_IN := QUERY_WHERE_IN || ' AND xnt.MAHANG IN (SELECT REGEXP_SUBSTR('''||MAHANG||''',''[^,]+'',1,LEVEL) FROM DUAL CONNECT BY REGEXP_SUBSTR('''||MAHANG||''',''[^,]+'' ,1,LEVEL) IS NOT NULL)';
    END IF;
    
    IF DIEUKIEN_NHOM = 'KHOHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' xnt.MAKHO AS MA,khohang.TENKHO AS TEN ';
        TABLE_JOIN := ' INNER JOIN KHOHANG khohang ON xnt.MAKHO = khohang.MAKHO ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY xnt.MAKHO,khohang.TENKHO' ;
        QUERY_ORDERBY := ' ORDER BY xnt.MAKHO';
    ELSIF DIEUKIEN_NHOM = 'LOAIHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' mathang.MALOAI AS MA,loaihang.TENLOAI AS TEN ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN LOAIHANG loaihang ON mathang.MALOAI = loaihang.MALOAI ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY mathang.MALOAI,loaihang.TENLOAI' ;
        QUERY_ORDERBY := ' ORDER BY mathang.MALOAI';
    ELSIF DIEUKIEN_NHOM = 'NHOMHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' mathang.MANHOM AS MA,nhomhang.TENNHOM AS TEN ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN NHOMHANG nhomhang ON mathang.MANHOM = nhomhang.MANHOM ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY nhomhang.MANHOM,nhomhang.TENNHOM' ;
        QUERY_ORDERBY := ' ORDER BY mathang.MANHOM';
    ELSIF DIEUKIEN_NHOM = 'NHACUNGCAP' THEN
        QUERY_SELECT := QUERY_SELECT || ' mathang.MANHACUNGCAP AS MA,nhacungcap.TENNHACUNGCAP AS TEN ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG INNER JOIN NHACUNGCAP nhacungcap ON mathang.MANHACUNGCAP = nhacungcap.MANHACUNGCAP ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY mathang.MANHACUNGCAP,nhacungcap.TENNHACUNGCAP' ;
        QUERY_ORDERBY := ' ORDER BY mathang.MANHACUNGCAP';
    ELSIF DIEUKIEN_NHOM = 'MATHANG' THEN
        QUERY_SELECT := QUERY_SELECT || ' xnt.MAHANG AS MA,mathang.TENHANG AS TEN ';
        TABLE_JOIN := ' INNER JOIN MATHANG mathang ON xnt.MAHANG = mathang.MAHANG ';
        QUERY_GROUPBY := QUERY_GROUPBY || ' GROUP BY xnt.MAHANG,mathang.TENHANG ' ;
        QUERY_ORDERBY := ' ORDER BY xnt.MAHANG';
    ELSE
        QUERY_GROUPBY := QUERY_GROUPBY || ' 1 AND 1 ';
    END IF;

    QUERY_STR := 'SELECT '||QUERY_SELECT||' ,ROUND(SUM(xnt.TONCUOIKYSL), 2) AS SOLUONG, ROUND(SUM(xnt.TONCUOIKYGT), 2) AS GIATRI 
    FROM '||TABLE_NAME||' xnt '||TABLE_JOIN||' '||QUERY_WHERE_IN||'
    WHERE xnt.UNITCODE = '''||UNITCODE||''' '||QUERY_GROUPBY || QUERY_ORDERBY ||'';
    BEGIN
--    DBMS_OUTPUT.put_line (QUERY_STR);  
    OPEN CUR_OUT FOR QUERY_STR;
    EXCEPTION
                WHEN NO_DATA_FOUND THEN
                 NULL;
                   WHEN OTHERS THEN
          NULL;
    END;
END XUATNHAPTON_TONKHO_TONGHOP;
 