// <auto-generated />
namespace ERBus.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UPDATE_UNITCODE_TO_TABLE_THANHTOAN_CHITIET : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UPDATE_UNITCODE_TO_TABLE_THANHTOAN_CHITIET));
        
        string IMigrationMetadata.Id
        {
            get { return "201906250800020_UPDATE_UNITCODE_TO_TABLE_THANHTOAN_CHITIET"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
