// <auto-generated />
namespace ERBus.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADD_COLUMN_SAPXEP_BOHANG_CHITIET : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_COLUMN_SAPXEP_BOHANG_CHITIET));
        
        string IMigrationMetadata.Id
        {
            get { return "201910101642575_ADD_COLUMN_SAPXEP_BOHANG_CHITIET"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
