// <auto-generated />
namespace ERBus.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ANHPT_CREATE_DATPHONG_UPDATE_PHONG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ANHPT_CREATE_DATPHONG_UPDATE_PHONG));
        
        string IMigrationMetadata.Id
        {
            get { return "201906091216189_ANHPT_CREATE_DATPHONG_UPDATE_PHONG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
