// <auto-generated />
namespace ERBus.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADDCOLUMN_TIENTRALAI_CHIETKHAU_THANHTOANPHONG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDCOLUMN_TIENTRALAI_CHIETKHAU_THANHTOANPHONG));
        
        string IMigrationMetadata.Id
        {
            get { return "201907131718568_ADDCOLUMN_TIENTRALAI_CHIETKHAU_THANHTOANPHONG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
